version: '3.3'

services:
      
  bb-db:
    image: ${dockerId}/bulletin-board-db:v4
    build:
      context: ./bulletin-board-db
    networks:
      - bb-net

  bb-app:
    image: ${dockerId}/bulletin-board-app:v4
    build:
      context: ./bulletin-board-app
    depends_on:
      - bb-db
    restart: on-failure
    networks:
      - bb-net

  bb-proxy:
    image: ${dockerId}/bulletin-board-proxy:v4
    build:
      context: ./bulletin-board-proxy
    ports:
      - "80:80"
    depends_on:
      - bb-app
    networks:
      - bb-net

networks:
  bb-net: