version: '3.3'

services:
      
  bb-db:
    image: ${dockerId}/bulletin-board-db:v4
    networks:
      - bb-net

  bb-app:
    image: ${dockerId}/bulletin-board-app:v4
    networks:
      - bb-net

  bb-proxy:
    image: ${dockerId}/bulletin-board-proxy:v4
    ports:
      - "80:80"
    networks:
      - bb-net
    deploy:
      mode: replicated
      replicas: 3

networks:
  bb-net: